### PR TITLE
Basic LSP implementation 

### PR DESCRIPTION
**Pull request by ehllie**
#179
I've set up the language server as a workspace for now since it makes working on the codebase easier that way. I did not copy the entire boilerplate project, but rather am just using them as reference and copying and pasting when necessary.

So far I've managed to get parsing errors displayed, and it was surprisingly straightforward

image

### CODE REVIEW

**Review by jfecher — COMMENTED** [review]
This looks amazing, thank you!

Is there any support you need from me to get a minimal version merged soon? As long as it compiles we can merge this in parts - we don't need to wait until the whole LSP is done.

I'm away from my computer ATM so I've yet to test this yet.

**Comment by ehllie** [comment]
I haven't done any work to make this a valid vscode extension like the template project does. Not sure if it would be in scope for the initial pr, but it would definitely make testing the server easier for people that do use it as their primary editor.

Other than that, I might need to change some `String` to `Arc<str>` since things like the `Ast`, and the references to paths it has need to outlive the request parameters, and it's a little tricky to do currently with those things only being borrowed.

**Review by ehllie — COMMENTED** [review]
So this commit is a little bit silly. Removing the lifetime from the `Location` type propagated out to almost every part of the codebase

**Comment by ehllie** [comment]
This should do be a good first step. Doing a massive rewrite and removing the lifetime parameters from `Location` and as a result `Ast` as well would probably be best left for a separate PR

**Comment by jfecher** [comment]
@ehllie I wonder if we need to get rid of those lifetime parameters or if we can instead keep them and avoid storing the Ast in the language server.

> I haven't done any work to make this a valid vscode extension like the template project does.

That's fine, I think a vscode extension should be a separate repo from the language server anyway. We also don't need to worry about other users testing until we get the basics down first. Since it sounds like we both use (neo)vim we can just focus on that for the moment.

**Review by jfecher — APPROVED** [review]
LGTM, we can use this as a base to build upon more features. Thank you!

**Pull request merged**
