### PR TITLE
Change the lambda syntax from . to ->

### LINKED ISSUE #67: Change the lambda syntax from `\a b.y` to `fn a b -> y`
This should be a relatively simple aesthetic change. Should only require changing the expected tokens for the `lambda` rule in the `parser/mod.rs` and adding the `fn` token to the lexer.

This is just a syntax change, so the current lambda `\a b. body` should be exactly equivalent to `fn a b -> body` in the new syntax.

Any places in the `examples` test directory that use lambdas will also need to have their syntax updated.

### PR DESCRIPTION
**Pull request by thehabbos007**
This closes #67 and #68 
Tests are passing

Hope this is what you had in mind :)

### CODE REVIEW

**Comment by jfecher** [comment]
Yes, this looks great, thank you :)

Reading this PR makes me realize how few tests there are with explicit function return types.

Out of curiosity, how did you find out about this project?

**Comment by thehabbos007** [comment]
I found the project on the "an open-source project I can contribute during this summer" reddit post on Rust. Was looking for something to work on for fun and this aligned well with what I find awesome!

**Comment by jfecher** [comment]
Ah, glad to hear it! Let me know if you're ever looking for or are stuck on a task, ante's codebase is getting fairly complex and I'm always happy to help.

If you want a place to stay up to date with ante's development, there's a #ante channel on the programming languages discord I sometimes use to talk about design/implementation on:  https://discord.gg/4Kjt3ZE
There's also the subreddit at /r/ante which I check regularly but to be honest I haven't updated it myself in years.

**Comment by thehabbos007** [comment]
Ah cool! Joined the discord and will look around some more here :)

**Pull request merged**
