### PR TITLE
ante-ls goto definition

### PR DESCRIPTION
**Pull request by ehllie**
Implements goto definition capability, and prevents the ls from panicking when the open document is empty. Also refactoring of utility functions to a separate module.

### CODE REVIEW

**Review by jfecher — APPROVED** [review]
LGTM, thank you once again!

**Comment by jfecher** [comment]
@ehllie do you mind tackling the Send errors with the futures next? Since one of the previous PRs I've been getting many of the following errors when building ante-ls:

```
error: future cannot be sent between threads safely
   --> ante-ls/src/main.rs:66:65
    |
66  |       async fn did_save(&self, params: DidSaveTextDocumentParams) {
    |  _________________________________________________________________^
67  | |         self.client.log_message(MessageType::LOG, format!("ante-ls did_save: {:?}", params)).await;
68  | |         if let Some(text) = params.text {
69  | |             let rope = Rope::from_str(&text);
...   |
74  | |         };
75  | |     }
    | |_____^ future created by async block is not `Send`
    |
    = help: the trait `Sync` is not implemented for `UnsafeCell<ante::parser::ast::Ast<'_>>`
```

**Comment by jfecher** [comment]
Ah, never mind. I did a get reset without also stashing. Should not have merged this PR. I'm going to revert this, then can you fix the compiler errors? I'm going to add a CI test that ante-ls builds as well since it seems it is not being checked.

**Comment by ehllie** [comment]
> @ehllie do you mind tackling the Send errors with the futures next? Since one of the previous PRs I've been getting many of the following errors when building ante-ls:
> 
> ```
> error: future cannot be sent between threads safely
>    --> ante-ls/src/main.rs:66:65
>     |
> 66  |       async fn did_save(&self, params: DidSaveTextDocumentParams) {
>     |  _________________________________________________________________^
> 67  | |         self.client.log_message(MessageType::LOG, format!("ante-ls did_save: {:?}", params)).await;
> 68  | |         if let Some(text) = params.text {
> 69  | |             let rope = Rope::from_str(&text);
> ...   |
> 74  | |         };
> 75  | |     }
>     | |_____^ future created by async block is not `Send`
>     |
>     = help: the trait `Sync` is not implemented for `UnsafeCell<ante::parser::ast::Ast<'_>>`
> ```

That's odd, I did not get any errors while building `ante-ls`. What `rustc` version are you using?

**Pull request merged**
